name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout main branch"
        uses: actions/checkout@v3

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          cache: 'npm'

      - name: "Install dependencies"
        run: npm install

      - name: "Running tests"
        run: npm run test

      - name: "Build release"
        run: npm run build

      - name: "Copy README.md"
        run: cp README.md dist/README.md

      - name: "Publish to NPM"
        run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}