name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout main branch"
        uses: actions/checkout@v3
      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          cache: 'yarn'
      - name: "Install Yarn"
        run: npm install -g yarn
      - name: "Install dependencies"
        run: yarn install
      - name: "Build release"
        run: yarn build
      - name: "Publish to NPM"
        run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}